### ISSUE TITLE
Kubectl/Helm completions not working with binenv

### ISSUE THREAD

**Issue by jmischler72** [devops-works/binenv#256]
Hello,
I have a Oh-my-zsh shell and ever since i installed my tools with binenv, i dont have any completions from the omz plugins kubectl and helm.
I tried the binenv completion steps but it still isn't working: 
```
Zsh:

# If shell completion is not already enabled in your environment you will need
# to enable it.  You can execute the following once:

$ echo "autoload -U compinit; compinit" >> ~/.zshrc

# To load completions for each session, execute once:
$ binenv completion zsh > "${fpath[1]}/_binenv"

# You will need to start a new shell for this setup to take effect.

```
The quickstart for linux didn't help either

**Comment by leucos** [comment]
Thanks or reporting this @jmischler72 
Indeed there is an issue with completion. We're looking into it.

**Comment by leucos** [comment]
Can you tell what version you are using ?

**Comment by vfricou** [comment]
Hello,

I’ve exactly same problem.

I’ve try with fresh zsh without any custom in zshrc just necessary for binenv (with completions) and kubectl (with completions).
Fresh binenv installation and fresh kubectl command installation through binenv.

It’s seem to completion couldn’t be correctly loaded/called due to shims call for kubectl commands, but I’m not sure.

Version for me :
- binenv : 0.19.10
- kubectl : 1.30.1 (tried with 1.29.3 and 1.28.10 too)
- zsh : 5.9

**Comment by leucos** [comment]
@jmischler72 @vfricou this should be fixed in v0.19.11.

Could you try to `binenv update && binenv install binenv` please ?

If you still have issues with the new version, please do the following:

```bash
export BASH_COMP_DEBUG_FILE=/tmp/binenvdebug
kubectl g<TAB><TAB>
```

and paste the `/tmp/binenvdebug` file here (please sanitize any sensitive information before).

Thanks !

**Comment by leucos** [comment]
Thanks ! 

This is weird; I have a different output here.

```
========= starting completion logic ==========
cur is p, words[*] is kubectl get p, #words[@] is 3, cword is 2
Truncated words[*]: kubectl get p,
lastParam p, lastChar p
Calling kubectl __complete get p
binenv called in shim mode for "kubectl __complete get p"
The completion directive is: 4
The completions are: persistentvolumeclaims
persistentvolumes
pods
podtemplates
provisioningrequests.autoscaling.x-k8s.io
prioritylevelconfigurations.flowcontrol.apiserver.k8s.io
pods.metrics.k8s.io
podmonitors.monitoring.coreos.com
probes.monitoring.coreos.com
prometheusagents.monitoring.coreos.com
prometheuses.monitoring.coreos.com
prometheusrules.monitoring.coreos.com
podmonitorings.monitoring.googleapis.com
podlogs.monitoring.grafana.com
poddisruptionbudgets.policy
priorityclasses.scheduling.k8s.io

Activating no file completion
__kubectl_handle_completion_types: COMP_TYPE is 63
```

What does `~/.binenv/binaries/kubectl/1.30.1 __complete get p` does return ?

And `kubectl __complete get p` ?

(if you're still on 1.30.1, otherwise please adjust version)

**Comment by leucos** [comment]
Oh well,I think this is because you do not have a connetion to a k8s API available, and the second level will check the available resources from the API:

```bash
$ kubectl __complete get p
E0627 11:08:11.427694 2431754 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```

So this sounds normal.

**Comment by vfricou** [comment]
For kubectl and helm completion on Linux, it’s OK

Effectively, with correct KUBECONFIG file exported, it’s OK on Linux.

But for MacOS issues stay present, and bash debug file export don’t work.

**Comment by leucos** [comment]
Assuming this is solved now.
