### ISSUE TITLE
Single installation command for installing binenv

### ISSUE THREAD

**Issue by Nex-Otaku** [devops-works/binenv#95]
Installing binenv should be simplified to single command.

We can implement it as installer bash script.

`wget -O - http://website.com/my-script.sh | bash`

or other, as described here: https://serverfault.com/a/890417/638586

Simpler installation is very important for user adoption.

**Comment by leucos** [comment]
@Nex-Otaku thanks for the suggestion.
However, I consider `wget | bash` as pretty unsafe.

Also, I'd rather not touch user rc files directly. People may have custom ways to manage them.

**Comment by Nex-Otaku** [comment]
This is what installation instructions are for Linux users

```
wget -q https://github.com/devops-works/binenv/releases/latest/download/binenv_linux_amd64 -O binenv
chmod +x binenv
./binenv update
./binenv install binenv
rm binenv
if [[ -n $BASH ]]; then ZESHELL=bash; fi
if [[ -n $ZSH_NAME ]]; then ZESHELL=zsh; fi
echo $ZESHELL
echo 'export PATH=~/.binenv:$PATH' >> ~/.${ZESHELL}rc
echo "source <(binenv completion ${ZESHELL})" >> ~/.${ZESHELL}rc
exec $SHELL
```

What I suggest is providing user with ability to run sh script from same repo that does exactly the same as above.

In both options user will copy, paste and run code from documentation. But it should be less copy-pasting actions to simplify process. One step instead of multiple steps.

99% of users will not modify installation steps, just installing as written in docs, and for those who want we can provide more detailed instruction.

**Comment by leucos** [comment]
Yes, I understand that. But for transparency and educational purposes, I'd rather have clear instructions that users can verify, instead of a shell file  they will probably `curl | bash` blindly.

I'd rather have people in control of what they are doing, and I do not want to mess with their rc files in their back.

They still can copy those 10 lines and paste them at once, or do it the yolo way with `curl -s https://raw.githubusercontent.com/devops-works/binenv/develop/README.md | grep -A15 '## Quick start' | grep -A10 'wget' | bash` of they really want to run a one liner ;) 

All in all, thanks for the suggestion :+1:
